Repository bundestagsbot/bundestagsbotjava, pull requests merged in 2020-06, with the labels that each got.

#11 added help command, regarding #1
  Dockerfile
  src/main/java/org/bundestagsbot/Commands/CommandHandler.java
  src/main/java/org/bundestagsbot/Commands/CommandHelp.java
  src/main/java/org/bundestagsbot/Commands/CommandSurvey.java
  src/main/java/org/bundestagsbot/Config/GuildConfig.java
  src/main/java/org/bundestagsbot/LocalUtils/FileSystem.java
Labels: command, ux

#12 implemented _survey command, regarding #1
  src/main/java/org/bundestagsbot/Commands/CommandSurvey.java
  src/main/java/org/bundestagsbot/Exceptions/CommandExecuteException.java
  src/main/java/org/bundestagsbot/Internals/Surveys/DawumJsonMapper/Parliament.java
  src/main/java/org/bundestagsbot/Internals/Surveys/DawumJsonMapper/RootDawumJson.java
  src/main/java/org/bundestagsbot/Internals/Surveys/DawumJsonMapper/Survey.java
Labels: command

#25 Rename readme.md to README.md
  README.md
Labels: documentation

#31 added some basic tests for internal objects, regarding #6
  src/test/java/org/bundestagsbot/embeds/ErrorLogEmbedTest.java
  src/test/java/org/bundestagsbot/embeds/FailureLogEmbedTest.java
  src/test/java/org/bundestagsbot/embeds/LogEmbedTest.java
  src/test/java/org/bundestagsbot/embeds/NeutralLogEmbedTest.java
  src/test/java/org/bundestagsbot/embeds/SuccessLogEmbedTest.java
  src/test/java/org/bundestagsbot/embeds/WarningLogEmbedTest.java
  src/test/java/org/bundestagsbot/internals/surveys/SurveyRequesterTest.java
  src/test/java/org/bundestagsbot/meta/AboutTest.java
  src/test/java/org/bundestagsbot/meta/VersionInfoTest.java
Labels: tests

#32 added post command, regarding #1
  src/main/java/org/bundestagsbot/commands/impl/CommandPost.java
  src/main/java/org/bundestagsbot/commands/impl/ECommandExecutor.java
Labels: command

#34 check for valid channel type before executing, fixed command construc…
  src/main/java/org/bundestagsbot/commands/Command.java
  src/main/java/org/bundestagsbot/commands/CommandHandler.java
  src/main/java/org/bundestagsbot/commands/impl/ACommandExecutor.java
  src/main/java/org/bundestagsbot/commands/impl/CommandPost.java
  src/main/java/org/bundestagsbot/commands/impl/ICommandExecutor.java
  src/main/java/org/bundestagsbot/listeners/MessageReceived.java
Labels: command, feature

#35 adjust format on help command
  src/main/java/org/bundestagsbot/commands/impl/CommandHelp.java
Labels: command, ux

#38 added singleton managment for config, added jackson mapper for config…
  README.md
  default-config.json
  src/main/java/org/bundestagsbot/BundestagsBot.java
  src/main/java/org/bundestagsbot/commands/Command.java
  src/main/java/org/bundestagsbot/config/GlobalConfig.java
  src/main/java/org/bundestagsbot/config/GuildConfig.java
  src/main/java/org/bundestagsbot/config/global/GlobalConfig.java
  src/main/java/org/bundestagsbot/config/global/GlobalConfigSingleton.java
  src/main/java/org/bundestagsbot/config/global/jsonmap/GlobalConfigJson.java
  src/main/java/org/bundestagsbot/config/guild/GuildConfig.java
  src/main/java/org/bundestagsbot/config/guild/GuildConfigSingleton.java
  src/main/java/org/bundestagsbot/config/guild/jsonmap/GuildConfigJson.java
  src/main/java/org/bundestagsbot/discord/DiscordClient.java
  src/main/java/org/bundestagsbot/discord/DiscordConnectionHandling.java
  src/main/java/org/bundestagsbot/exceptions/ConfigInvalidException.java
  src/main/java/org/bundestagsbot/localUtils/FileSystem.java
Labels: feature

#42 removed guild config and using only one config/bot per instance
  default-config.json
  src/main/java/org/bundestagsbot/BundestagsBot.java
  src/main/java/org/bundestagsbot/commands/Command.java
  src/main/java/org/bundestagsbot/config/BotConfig.java
  src/main/java/org/bundestagsbot/config/BotConfigSingleton.java
  src/main/java/org/bundestagsbot/config/global/GlobalConfigSingleton.java
  src/main/java/org/bundestagsbot/config/guild/GuildConfig.java
  src/main/java/org/bundestagsbot/config/guild/GuildConfigSingleton.java
  src/main/java/org/bundestagsbot/config/guild/jsonmap/GuildConfigJson.java
  src/main/java/org/bundestagsbot/config/jsonmap/BotConfigJson.java
  src/main/java/org/bundestagsbot/discord/DiscordClient.java
  src/main/java/org/bundestagsbot/discord/DiscordConnectionHandling.java
Labels: breaking

#44 Add welcome message
  default-config.json
  src/main/java/org/bundestagsbot/commands/CommandHandler.java
  src/main/java/org/bundestagsbot/config/jsonmap/BotConfigJson.java
  src/main/java/org/bundestagsbot/discord/DiscordClient.java
  src/main/java/org/bundestagsbot/listeners/GuildMemberJoin.java
  src/main/java/org/bundestagsbot/listeners/MessageReceived.java
Labels: feature

#43 added suggestion handling, reacting with thumbs up and down, no comma…
  default-config.json
  src/main/java/org/bundestagsbot/commands/CommandHandler.java
  src/main/java/org/bundestagsbot/config/jsonmap/BotConfigJson.java
  src/main/java/org/bundestagsbot/internals/suggestions/SuggestionHandler.java
  src/main/java/org/bundestagsbot/listeners/MessageReceived.java
Labels: feature

#45 fixes #17, option to assign and remove roles on reaction in specified…
  default-config.json
  src/main/java/org/bundestagsbot/config/jsonmap/BotConfigJson.java
  src/main/java/org/bundestagsbot/discord/DiscordClient.java
  src/main/java/org/bundestagsbot/discord/DiscordConnectionHandling.java
  src/main/java/org/bundestagsbot/internals/rolesassignment/RoleReactions.java
  src/main/java/org/bundestagsbot/internals/startupcheck/ConfigChecks.java
  src/main/java/org/bundestagsbot/listeners/GuildMessageReaction.java
Labels: feature

#47 implemented _role command, former known as "i am", regarding #1
  src/main/java/org/bundestagsbot/commands/impl/ACommandExecutor.java
  src/main/java/org/bundestagsbot/commands/impl/CommandRole.java
  src/main/java/org/bundestagsbot/commands/impl/ECommandExecutor.java
  src/main/java/org/bundestagsbot/config/jsonmap/BotConfigJson.java
  src/main/java/org/bundestagsbot/internals/startupcheck/ConfigChecks.java
Labels: command
